sudo: false

language: python

python:
  - "3.6"

script:
  - echo "Nothing to test here, move along!"

before_deploy:
  # Decrypt secrets
  - openssl aes-256-cbc -K $encrypted_f21506e5a524_key -iv $encrypted_f21506e5a524_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  # Enable ssh agent and add ssh key to use for deployment
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 0600 dev-deployment2
  - ssh-add dev-deployment2
  - ssh-add -l
  # Install Ansible
  - pip install ansible
  # Deploy to Dev
  - export ANSIBLE_HOST_KEY_CHECKING=False

deploy:
  provider: script
  skip_cleanup: true
  script: ansible-playbook -i hosts_dev full-site.yml --vault-password-file=vault-pass --extra-vars "ansible_user=automation"
  on:
    branch: pedro/auto-deploy
