- name: purge cloudflare cache
  shell: 'curl -X POST "https://api.cloudflare.com/client/v4/zones/{{item}}/purge_cache" -H "Authorization: Bearer {{cloudflare_api_token}}" -H "Content-Type: application/json" --data "{\"purge_everything\":true}"'
  with_items:
    - "{{cloudflare_echaloasuerte_id}}"
    - "{{cloudflare_chooserandom_id}}"

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
  become: yes
